name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run composer install
        run: |
          composer clear-cache
          composer install --no-dev --prefer-dist
      - name: Install npm packages
        run: |
          npm ci
      - name: Build
        run: |
          npm install
          npm run build
          npm run i18n
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release asset
        if: |
          steps.semantic.outputs.new-release-published == 'true' &&
          startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
